2019-11-24 16:00:14,463 ERROR: Exception on /recipe/Salad [POST] [in c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 717, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1782, in process
    value = _strict_as_bool(value)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1757, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
TypeError: Not a boolean value: <wtforms.fields.core.BooleanField object at 0x000001F357806940>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\python\git\microblog\app\routes.py", line 257, in recipe
    db.session.commit()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 1026, in commit
    self.transaction.commit()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 493, in commit
    self._prepare_impl()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 472, in _prepare_impl
    self.session.flush()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 2458, in flush
    self._flush(objects)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 2596, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\compat.py", line 129, in reraise
    raise value
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\session.py", line 2556, in _flush
    flush_context.execute()
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\orm\persistence.py", line 978, in _emit_update_statements
    statement, multiparams
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 717, in _init_compiled
    param.append(processors[key](compiled_params[key]))
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1782, in process
    value = _strict_as_bool(value)
  File "c:\users\andy\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1757, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % value)
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: <wtforms.fields.core.BooleanField object at 0x000001F357806940>
[SQL: UPDATE recipe SET "isBreakfast"=? WHERE recipe.id = ?]
[parameters: [{'isBreakfast': <wtforms.fields.core.BooleanField object at 0x000001F357806940>, 'recipe_id': 10}]]
2019-11-24 16:10:16,411 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:12:09,603 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:14:56,678 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:17:21,217 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:18:29,372 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:20:30,029 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:30:16,728 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 16:34:33,509 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:16:20,087 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:18:12,368 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:19:26,927 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:20:15,086 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:20:40,402 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:22:51,339 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:23:45,662 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:24:28,786 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:26:17,798 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:27:33,871 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:28:38,269 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:30:19,542 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:32:19,915 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:41:14,756 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
2019-11-24 19:42:21,822 INFO: Microblog startup [in C:\python\git\microblog\app\__init__.py:54]
