2019-12-03 12:09:21,713 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 322, in mealplan
    form = MealplanForm()
  File "c:\python\git\microblog\winvenv\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_wtf\form.py", line 88, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\python\git\microblog\winvenv\lib\site-packages\wtforms\form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\python\git\microblog\winvenv\lib\site-packages\wtforms\form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\python\git\microblog\winvenv\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\python\git\microblog\winvenv\lib\site-packages\wtforms\fields\core.py", line 353, in bind
    return self.field_class(*self.args, **kw)
TypeError: __init__() got multiple values for argument 'label'
2019-12-03 12:09:44,956 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:11:58,664 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:14:05,747 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:14:09,333 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 327, in mealplan
    return render_template('mealplan.html', form=form)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\python\git\microblog\winvenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\python\git\microblog\winvenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\python\git\microblog\winvenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\git\microblog\app\templates\mealplan.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Python\git\microblog\app\templates\base.html", line 51, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Python\git\microblog\app\templates\mealplan.html", line 11, in block "app_content"
    {{ form.submit(class="btn btn-primary") }}
jinja2.exceptions.UndefinedError: 'app.forms.MealplanForm object' has no attribute 'submit'
2019-12-03 12:14:32,026 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:15:51,231 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:16:31,791 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:26:45,961 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:28:18,437 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:28:58,934 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 12:51:12,490 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:01:07,370 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:01:11,919 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 323, in mealplan
    breakfast_recipes = Recipe.query.order_by(Recipe.name).filter_by(Recipe.isBreakfast)
TypeError: filter_by() takes 1 positional argument but 2 were given
2019-12-03 13:02:05,756 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:02:09,027 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 323, in mealplan
    breakfast_recipes = Recipe.query.filter_by(Recipe.isBreakfast)
TypeError: filter_by() takes 1 positional argument but 2 were given
2019-12-03 13:02:27,802 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
