2019-12-03 13:02:30,663 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 323, in mealplan
    breakfast_recipes = Recipe.query.filter_by(isBreakfast)
NameError: name 'isBreakfast' is not defined
2019-12-03 13:04:01,863 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:17:55,903 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:18:14,769 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:18:28,594 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:18:38,209 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:23:53,545 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:24:04,496 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:27:07,988 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:27:11,883 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 337, in mealplan
    breakfast_recipes = shuffle(Recipe.query.filter_by(isBreakfast=True))
  File "C:\Python\lib\random.py", line 271, in shuffle
    for i in reversed(range(1, len(x))):
TypeError: object of type 'BaseQuery' has no len()
2019-12-03 13:28:17,058 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:28:27,732 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:28:32,414 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 341, in mealplan
    print(choice(lunch_recipes))
  File "C:\Python\lib\random.py", line 255, in choice
    i = self._randbelow(len(seq))
TypeError: object of type 'BaseQuery' has no len()
2019-12-03 13:31:30,183 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:31:34,251 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 340, in mealplan
    print(choice(lunch_recipes))
NameError: name 'choice' is not defined
2019-12-03 13:31:53,313 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:40:55,787 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:40:59,874 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 337, in mealplan
    breakfast_recipes = shuffle(Recipe.query.filter_by(isBreakfast=True).all())[:5]
TypeError: 'NoneType' object is not subscriptable
2019-12-03 13:41:43,803 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:41:48,569 ERROR: Exception on /mealplan [GET] [in c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python\git\microblog\winvenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Python\git\microblog\app\routes.py", line 342, in mealplan
    day.breakfast = breakfast_recipes.pop()
AttributeError: 'NoneType' object has no attribute 'pop'
2019-12-03 13:42:29,178 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:42:51,469 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:46:55,706 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:47:45,039 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
2019-12-03 13:48:34,135 INFO: Microblog startup [in C:\Python\git\microblog\app\__init__.py:53]
